<?php

/**
 * Implements hook_init().
 */
function selenium_init() {
  module_load_include('inc', '/classes/selenium_core.class', 'selenium');
  module_load_include('inc', '/classes/drupal_selenium_web_test_case.class', 'selenium');
}

/**
 * Implementation of hook_form_alter().
 */
function selenium_form_simpletest_settings_form_alter(&$form, &$form_state) {
  $form['selenium'] = array(
    '#type' => 'fieldset',
    '#title' => t('Selenium settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#tree' => FALSE,
  );

  $form['selenium']['selenium_server_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Selenium server host and port'),
    '#description' => t('Format is HOST:PORT (example: localhost:4444).'),
    '#default_value' => variable_get('selenium_server_host', 'localhost:4444'),
  );
}
